#!/bin/bash

# Comandos para ejecutar en Railway
echo "=== RAILWAY SETUP COMMANDS ==="
echo ""
echo "1. Limpiar caches:"
echo "php artisan cache:clear"
echo "php artisan config:clear"
echo "php artisan route:clear"
echo "php artisan view:clear"
echo ""
echo "2. Ejecutar migraciones:"
echo "php artisan migrate --force"
echo ""
echo "3. Verificar tablas (opcional):"
echo "php artisan tinker"
echo "Schema::hasTable('usuarios')"
echo "Schema::hasTable('perfiles')"
echo "Schema::hasTable('tratamientos')"
echo "exit"
echo ""
echo "4. Si hay problemas con migraciones, reset completo:"
echo "php artisan migrate:fresh --force"
echo ""
echo "=== EJECUTAR EN RAILWAY SHELL ==="
